### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by ris58h** [LoPablo/MiddleClick#3]
First of all, thank you for your work!

Could you add a release so other people could just download it without building?

**Comment by longnd** [comment]
There are releases already
https://github.com/LoPablo/MiddleClick/releases

**Comment by ris58h** [comment]
@longnd This fork has some unmerged work (https://github.com/cl3m/MiddleClick/pull/27) in it.
Edit: I was confused. The releases link is what i was looking for.

**Comment by longnd** [comment]
if you want the [original repo](https://github.com/cl3m/MiddleClick) makes a release then you should create an issue there.
This is a forked repo and the author already released their own version.

**Comment by LoPablo** [comment]
I waited with the PR but since it was not merged I released a version of my own. The post from @longnd says it all.
